#
# This file contains configuration flags to customize your site
#

# Site details (displayed in the header)
author: De Vitaliteits Boutique
name: De Vitaliteits Boutique Blog
title: De Vitaliteits Boutique Blog
description: "At De Vitaliteitsboutique, I help women boost their vitality from the inside out. By focusing on six essential areas – breathing, stress, sleep, nutrition, movement, and the immune system – I offer personal and practical guidance toward more energy, balance, and resilience. With care, calm, and a clear approach, I support women in feeling good in both body and mind."
keywords: "Sleepcoach, Sleeptherapist, Hormone therapist, Hormone expert, Stress therapist, stress coach, breathing therapist, Holistic hormone coach, Vitality, Sleeping problems, Hormone problems, Menopause, PMS, Hormone balance, Sleep and hormones, Holistic therapist, insomnia, Women’s holistic health, Burnout prevention for women, Work-life balance for women"
logo: images/logo.jpeg

# Company details
company:
  analytics:
    google_id: 
    google_ads_id: 
    microsoft_clarity_id: 
  cta:
    text: "Learn More"
    url: "https://www.haven51.nl/slaap-hormoon-oefentherapeut"
  socials:
    youtube: 
    instagram: 
    facebook: 
    tiktok: 
    x: 
    linkedin: 
    pinterest: 
    telegram: 
    discord: 
    github: 
    email: 
    phone: 
  icon_size: "24"
  colors:
    main:
      background: "#157672"
      foreground: "#edf1e8"
    body:
      background: "#157672"
      foreground: "#edf1e8"
    accent: "#edf1e8"
  fonts:
    google:
      - "Poppins:ital,wght@0,100..900;1,100..900"
    heading: "'Poppins'"
    body: "'Poppins'"

# Navigation items
navigation:
  header:
    - title: "Our Sleep Formula"
      url: "https://devitaliteitsboutique.nl/slaapformule/"
    - title: "1-on-1 Coaching"
      url: "https://devitaliteitsboutique.nl/slaapproblemen-1-op-1-begeleiding/"
    - title: "Get Instant Help"
      url: "https://devitaliteitsboutique.nl/hulp-hormonale-klachten/"
    - title: "Learn More"
      url: "https://devitaliteitsboutique.nl/"
  footer:
    - title: "Terms and Conditions"
      url: "/terms-and-conditions"
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Cookie Policy"
      url: "/cookie-policy"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://devitaliteitsboutique-blog.github.io

# Paginate after X amount of posts
paginate: 10

#
# NOTHING TO CHANGE BEYOND THIS POINT
#

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# ONLY NECESSARY ON SUB-PAGE / GITHUB-BASED HOSTING
baseurl: 

# Theme used as a base
theme: jekyll-swiss

# Slug of paginated page
paginate_path: "/page-:num/"

# Permalink slug (DO NOT TOUCH)
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Disable Github Metadata plugin
github: [metadata]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom RSS feed
  - jekyll-paginate # Support pagination of posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - __init/
  - init_mac.command
  - init_windows.bat